#!/usr/bin/env python3
"""Generate src/cartdb.h: per-IC SHA1 database of every known Naomi/Naomi 2
cartridge game, extracted from `mame -listxml` metadata.

Usage: gen_cartdb.py <mamelist.xml | -> [out.h]
("-" reads stdin: mame -listxml | gen_cartdb.py - src/cartdb.h, which
spares writing the ~300 MB XML to disk)

Chip names come from the MAME file names, whose extension is the chip's
silkscreen position ("mpr-23083.ic31" -> ic31). The exceptions:
  - "ic8.bin" (a few prototypes and later releases): the IC is the stem;
  - "opr-24067.18" (Club Kart Prize): a bare number, "ic" is added;
  - the Namco-developed carts ("maz1ma1.4m"): a PCB grid position,
    kept as it is, since that is what the board shows.
Two more MAME habits are folded:
  - the same file loaded at two offsets (mvsc2's ic31) is one chip:
    hashed once;
  - an alternative dump at the same offset (f355twn2's "_alt" ic22) is a
    second known content for that chip: the game is listed once more with
    it, so either version identifies and verifies."""
import re
import sys
import xml.etree.ElementTree as ET

xml_path = sys.argv[1]
out_path = sys.argv[2] if len(sys.argv) > 2 else "src/cartdb.h"
src_xml = sys.stdin.buffer if xml_path == "-" else xml_path


def ic_name(fname):
    stem, _, ext = fname.rpartition(".")
    if not stem:
        return fname[:7]
    if re.fullmatch(r"ic\d+s?", ext):
        return ext
    if ext == "bin" and re.fullmatch(r"ic\d+s?", stem):
        return stem
    if re.fullmatch(r"\d+s?", ext):
        return "ic" + ext
    return ext[:7]

games = []
for ev, el in ET.iterparse(src_xml, events=("end",)):
    if el.tag != "machine":
        continue
    src = el.get("sourcefile") or ""
    if "naomi" not in src:
        el.clear()
        continue
    ics = []
    for r in el.findall("rom"):
        if r.get("region") != "rom_board" or not r.get("sha1"):
            continue
        if r.get("status") == "nodump":
            continue
        ics.append({
            "off": int(r.get("offset", "0"), 16),
            "size": int(r.get("size", "0")),
            "sha1": r.get("sha1"),
            "ic": ic_name(r.get("name")),
        })
    if ics:
        ics.sort(key=lambda x: x["off"])
        # one chip mapped twice: keep its first appearance
        seen, uniq = set(), []
        for i in ics:
            if (i["sha1"], i["ic"]) not in seen:
                seen.add((i["sha1"], i["ic"]))
                uniq.append(i)
        # alternative dumps at one offset: a variant of the game per extra
        base, alts = [], []
        for i in uniq:
            if base and base[-1]["off"] == i["off"] and base[-1]["size"] == i["size"]:
                alts.append(i)
            else:
                base.append(i)
        desc = (el.findtext("description") or el.get("name"))[:31]
        games.append({"name": el.get("name"), "desc": desc, "ics": base})
        for k, a in enumerate(alts):
            var = [a if (i["off"] == a["off"]) else i for i in base]
            games.append({"name": f'{el.get("name")}~{k}',
                          "desc": desc[:25].rstrip() + " (alt)", "ics": var})
    el.clear()

games.sort(key=lambda g: g["name"])
# identification checkpoints: distinct sizes of offset-0 ICs
first_sizes = sorted({g["ics"][0]["size"] for g in games
                      if g["ics"][0]["off"] == 0})

flat = []
out = ["/* Auto-generated by tools/gen_cartdb.py from mame -listxml.",
       " * Per-IC SHA1 database of known Naomi/Naomi2 cartridge games. */",
       "#ifndef CARTDB_H", "#define CARTDB_H", ""]

titles, gfirst, gnics = [], [], []
for g in games:
    gfirst.append(len(flat))
    gnics.append(len(g["ics"]))
    titles.append(g["desc"])
    flat.extend(g["ics"])

out.append(f"#define CARTDB_NGAMES {len(games)}")
out.append(f"#define CARTDB_NICS {len(flat)}")
out.append(f"#define CARTDB_NFIRST {len(first_sizes)}")
out.append("")
out.append("static const u32 cartdb_first_sizes[CARTDB_NFIRST] = {")
out.append("    " + ", ".join(f"0x{s:X}" for s in first_sizes))
out.append("};")

def cstr(s):
    return '"' + s.replace("\\", "").replace('"', "'") + '"'

out.append("static const char cartdb_title[CARTDB_NGAMES][32] = {")
out.append(",\n".join("    " + cstr(t) for t in titles))
out.append("};")
out.append("static const u16 cartdb_game_first[CARTDB_NGAMES] = {")
out.append("    " + ", ".join(str(v) for v in gfirst))
out.append("};")
out.append("static const u16 cartdb_game_nics[CARTDB_NGAMES] = {")
out.append("    " + ", ".join(str(v) for v in gnics))
out.append("};")
out.append("static const u32 cartdb_ic_off[CARTDB_NICS] = {")
out.append("    " + ", ".join(f"0x{i['off']:X}" for i in flat))
out.append("};")
out.append("static const u32 cartdb_ic_size[CARTDB_NICS] = {")
out.append("    " + ", ".join(f"0x{i['size']:X}" for i in flat))
out.append("};")
out.append("static const char cartdb_ic_name[CARTDB_NICS][8] = {")
out.append(",\n".join('    "' + i["ic"] + '"' for i in flat))
out.append("};")
out.append("static const u8 cartdb_sha1[CARTDB_NICS][20] = {")
rows = []
for i in flat:
    b = bytes.fromhex(i["sha1"])
    rows.append("    {" + ",".join(f"0x{x:02X}" for x in b) + "}")
out.append(",\n".join(rows))
out.append("};")
out.append("")
out.append("#endif")

with open(out_path, "w") as f:
    f.write("\n".join(out) + "\n")
print(f"{len(games)} games, {len(flat)} ICs, "
      f"first sizes: {[hex(s) for s in first_sizes]}")
