#!/usr/bin/env python3
"""Generate src/cartdb.h: per-IC SHA1 database of every known Naomi/Naomi 2
cartridge game, extracted from `mame -listxml` metadata.

Usage: gen_cartdb.py <mamelist.xml> [out.h]
(regenerate the XML with: mame -listxml > mamelist.xml)"""
import sys
import xml.etree.ElementTree as ET

xml_path = sys.argv[1]
out_path = sys.argv[2] if len(sys.argv) > 2 else "src/cartdb.h"

games = []
for ev, el in ET.iterparse(xml_path, events=("end",)):
    if el.tag != "machine":
        continue
    src = el.get("sourcefile") or ""
    if "naomi" not in src:
        el.clear()
        continue
    ics = []
    for r in el.findall("rom"):
        if r.get("region") != "rom_board" or not r.get("sha1"):
            continue
        if r.get("status") == "nodump":
            continue
        name = r.get("name")
        icname = name.rsplit(".", 1)[-1] if "." in name else name
        ics.append({
            "off": int(r.get("offset", "0"), 16),
            "size": int(r.get("size", "0")),
            "sha1": r.get("sha1"),
            "ic": icname[:7],
        })
    if ics:
        ics.sort(key=lambda x: x["off"])
        desc = (el.findtext("description") or el.get("name"))[:31]
        games.append({"name": el.get("name"), "desc": desc, "ics": ics})
    el.clear()

games.sort(key=lambda g: g["name"])
# identification checkpoints: distinct sizes of offset-0 ICs
first_sizes = sorted({g["ics"][0]["size"] for g in games
                      if g["ics"][0]["off"] == 0})

flat = []
out = ["/* Auto-generated by tools/gen_cartdb.py from mame -listxml.",
       " * Per-IC SHA1 database of known Naomi/Naomi2 cartridge games. */",
       "#ifndef CARTDB_H", "#define CARTDB_H", ""]

titles, gfirst, gnics = [], [], []
for g in games:
    gfirst.append(len(flat))
    gnics.append(len(g["ics"]))
    titles.append(g["desc"])
    flat.extend(g["ics"])

out.append(f"#define CARTDB_NGAMES {len(games)}")
out.append(f"#define CARTDB_NICS {len(flat)}")
out.append(f"#define CARTDB_NFIRST {len(first_sizes)}")
out.append("")
out.append("static const u32 cartdb_first_sizes[CARTDB_NFIRST] = {")
out.append("    " + ", ".join(f"0x{s:X}" for s in first_sizes))
out.append("};")

def cstr(s):
    return '"' + s.replace("\\", "").replace('"', "'") + '"'

out.append("static const char cartdb_title[CARTDB_NGAMES][32] = {")
out.append(",\n".join("    " + cstr(t) for t in titles))
out.append("};")
out.append("static const u16 cartdb_game_first[CARTDB_NGAMES] = {")
out.append("    " + ", ".join(str(v) for v in gfirst))
out.append("};")
out.append("static const u16 cartdb_game_nics[CARTDB_NGAMES] = {")
out.append("    " + ", ".join(str(v) for v in gnics))
out.append("};")
out.append("static const u32 cartdb_ic_off[CARTDB_NICS] = {")
out.append("    " + ", ".join(f"0x{i['off']:X}" for i in flat))
out.append("};")
out.append("static const u32 cartdb_ic_size[CARTDB_NICS] = {")
out.append("    " + ", ".join(f"0x{i['size']:X}" for i in flat))
out.append("};")
out.append("static const char cartdb_ic_name[CARTDB_NICS][8] = {")
out.append(",\n".join('    "' + i["ic"] + '"' for i in flat))
out.append("};")
out.append("static const u8 cartdb_sha1[CARTDB_NICS][20] = {")
rows = []
for i in flat:
    b = bytes.fromhex(i["sha1"])
    rows.append("    {" + ",".join(f"0x{x:02X}" for x in b) + "}")
out.append(",\n".join(rows))
out.append("};")
out.append("")
out.append("#endif")

with open(out_path, "w") as f:
    f.write("\n".join(out) + "\n")
print(f"{len(games)} games, {len(flat)} ICs, "
      f"first sizes: {[hex(s) for s in first_sizes]}")
