#!/usr/bin/env python3
"""Generate spoken diagnostic clips as signed 16-bit LE 22050 Hz mono PCM
embedded in a C header (src/audio_clips.h) for the AICA to play (PCMS=0).

Engine: Piper neural TTS (tools/.venv) with the fr_FR-siwis-medium voice.
Falls back to espeak-ng if Piper/model are missing."""
import subprocess, tempfile, os, sys, shutil

HERE  = os.path.dirname(os.path.abspath(__file__))
PIPER = os.path.join(HERE, ".venv", "bin", "piper")
MODEL = os.path.join(HERE, "voices", "fr_FR-siwis-medium.onnx")

CLIPS = [
    ("tests_done",  "Fin des tests."),
    ("audio_ok",    "Sortie audio fonctionnelle."),
    ("cpu_cache",   "Mémoire cache du processeur."),
    ("cpu_ram",     "Mémoire principale."),
    ("data_bus",    "Bus de données."),
    ("addr_bus",    "Bus d'adresses."),
    ("sound_ram",   "Mémoire son."),
    ("ok",          "Test réussi."),
    ("fail",        "Test échoué."),
    ("defect",      "défectueuse."),
    ("num_1",       "numéro un,"),
    ("num_2",       "numéro deux,"),
    ("num_3",       "numéro trois,"),
    ("num_4",       "numéro quatre,"),
    ("num_5",       "numéro cinq,"),
    ("num_6",       "numéro six,"),
    ("num_7",       "numéro sept,"),
    ("num_8",       "numéro huit,"),
    # silkscreen IC designators (mapping extracted from the original BIOS
    # RAM TEST tables; WORK lane order still to be confirmed on real HW)
    ("ic_9",        "I C neuf,"),
    ("ic_10",       "I C dix,"),
    ("ic_11",       "I C onze,"),
    ("ic_12",       "I C douze,"),
    ("ic_16",       "I C seize,"),
    ("ic_18",       "I C dix-huit,"),
    ("ic_20",       "I C vingt,"),
    ("ic_22",       "I C vingt-deux,"),
    ("ic_29",       "I C vingt-neuf,"),
    ("ic_35",       "I C trente-cinq,"),
    ("ic_27",       "I C vingt-sept,"),
    ("bios",        "Mémoire morte bios."),
    ("vram",        "Mémoire vidéo."),
    ("sram",        "Mémoire de sauvegarde."),
    ("rtc",         "Horloge temps réel."),
    ("dimm",        "Carte dime."),
    ("absent",      "absente."),
    ("present",     "présente."),
    ("jvs",         "Contrôleur d'entrées sorties, émi."),
    ("naomi1",      "Carte Naomi un."),
    ("naomi2",      "Carte Naomi deux."),
    ("board_unk",   "Carte non identifiée."),
]

RATE = 22050
MAX_SAMPLES = 0xFFF0            # AICA LEA is 16-bit

def tts(text, wav):
    if os.path.exists(PIPER) and os.path.exists(MODEL):
        subprocess.run([PIPER, "-m", MODEL, "-f", wav],
                       input=text.encode(), check=True,
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    else:
        print("WARNING: Piper missing, falling back to espeak-ng")
        subprocess.run(["espeak-ng", "-v", "fr", "-s", "150", "-w", wav, text],
                       check=True)

out = ["/* Auto-generated by tools/gen_audio.py — do not edit.",
       f" * Signed 16-bit LE mono PCM @ {RATE} Hz for AICA (PCMS=0).",
       " * Voice: Piper fr_FR-siwis-medium (neural TTS). */",
       "#ifndef AUDIO_CLIPS_H", "#define AUDIO_CLIPS_H", ""]

names = []
total = 0
for name, text in CLIPS:
    with tempfile.TemporaryDirectory() as td:
        wav = os.path.join(td, "c.wav")
        raw = os.path.join(td, "c.raw")
        tts(text, wav)
        subprocess.run(["sox", wav, "-r", str(RATE), "-c", "1",
                        "-e", "signed-integer", "-b", "16", "-t", "raw", raw,
                        "norm", "-2", "silence", "1", "0.05", "0.3%",
                        "reverse", "silence", "1", "0.05", "0.3%", "reverse"],
                       check=True)
        data = open(raw, "rb").read()
    if len(data) > MAX_SAMPLES * 2:
        print(f"WARNING: {name} truncated to 2.9s (AICA LEA is 16-bit)")
        data = data[:MAX_SAMPLES * 2]
    if len(data) % 4:
        data += b"\0" * (4 - len(data) % 4)
    total += len(data)
    arr = ", ".join(str(b - 256 if b > 127 else b) for b in data)
    out.append("static const signed char __attribute__((aligned(4))) "
               f"clip_{name}[] = {{ {arr} }};")
    names.append(name)
    print(f"{name}: {len(data)} bytes ({len(data)/2/RATE:.2f} s)")

print(f"total embedded audio: {total} bytes")
out += ["", "typedef struct { const signed char *pcm; unsigned len; } audio_clip;",
        "enum {"]
out += [f"    CLIP_{n.upper()}," for n in names]
out += ["    CLIP_COUNT", "};", "",
        "static const audio_clip audio_clips[CLIP_COUNT] = {"]
out += [f"    {{ clip_{n}, sizeof clip_{n} }}," for n in names]
out += ["};", "", "#endif"]

with open(sys.argv[1] if len(sys.argv) > 1 else "src/audio_clips.h", "w") as f:
    f.write("\n".join(out) + "\n")
