#!/usr/bin/env python3
"""Assemble arm/aica_arm_test.S for the AICA's ARM7 and emit it as a C array.

Generated and committed, like src/mie_prog.h: the ROM builds with the SH-4
toolchain alone, arm-none-eabi-as is needed only to change the ARM side.
The program is linked at 0 (the ARM7's reset vector in sound RAM).

Usage: gen_armprog.py [arm/aica_arm_test.S] [src/arm_prog.h]"""
import os, subprocess, sys, tempfile

src = sys.argv[1] if len(sys.argv) > 1 else "arm/aica_arm_test.S"
out = sys.argv[2] if len(sys.argv) > 2 else "src/arm_prog.h"
with tempfile.TemporaryDirectory() as td:
    o, e, b = (os.path.join(td, n) for n in ("a.o", "a.elf", "a.bin"))
    subprocess.run(["arm-none-eabi-as", "-march=armv3", "-EL", src, "-o", o],
                   check=True)
    subprocess.run(["arm-none-eabi-ld", "-Ttext=0", "-EL", o, "-o", e],
                   check=True)
    subprocess.run(["arm-none-eabi-objcopy", "-O", "binary", e, b], check=True)
    data = open(b, "rb").read()
if len(data) > 0x2000:
    sys.exit(f"ARM program is {len(data)} bytes: it must stay below the "
             "scratch area at 0x2000")
data += b"\0" * (-len(data) % 4)
words = [int.from_bytes(data[i:i + 4], "little") for i in range(0, len(data), 4)]
lines = ["/* Generated by tools/gen_armprog.py from arm/aica_arm_test.S -- do not",
         " * edit. ARM7DI (ARMv3) code for the AICA, linked at sound RAM 0. */",
         "#ifndef ARM_PROG_H", "#define ARM_PROG_H", "",
         f"#define ARM_PROG_WORDS {len(words)}",
         "static const u32 arm_prog[ARM_PROG_WORDS] = {"]
for i in range(0, len(words), 6):
    lines.append("    " + ", ".join(f"0x{w:08X}" for w in words[i:i + 6]) + ",")
lines += ["};", "", "#endif", ""]
open(out, "w").write("\n".join(lines))
print(f"{out}: {len(data)} bytes of ARM code")
