#!/usr/bin/env python3
"""Assemble src/mie_prog.z80 and emit it as a C array.

Kept as a generated-and-committed source, like the audio clips and the
cartridge database: the ROM builds with nothing but the SH-4 toolchain, and
z80asm is only needed by whoever changes the Z80 side.

Usage: gen_mieprog.py [src/mie_prog.z80] [src/mie_prog.h]
"""
import subprocess, sys, tempfile, os

src = sys.argv[1] if len(sys.argv) > 1 else "src/mie_prog.z80"
out = sys.argv[2] if len(sys.argv) > 2 else "src/mie_prog.h"

# the load address the program is assembled for, taken from its own org
org = None
for line in open(src, encoding="utf-8"):
    s = line.split(";")[0].strip()
    if s.lower().startswith("org "):
        org = int(s[4:].strip().rstrip("hH"), 16)
        break
if org is None:
    sys.exit("no org directive in " + src)

with tempfile.TemporaryDirectory() as td:
    binf = os.path.join(td, "mie.bin")
    subprocess.run(["z80asm", "-o", binf, src], check=True)
    blob = open(binf, "rb").read()

rows = []
for i in range(0, len(blob), 12):
    rows.append("    " + ", ".join("0x%02X" % b for b in blob[i:i + 12]) + ",")

open(out, "w", encoding="utf-8").write(
    "/* Auto-generated by tools/gen_mieprog.py from %s -- do not edit.\n"
    " * Z80 program uploaded into the MIE; see the .z80 source for what it\n"
    " * does and why the stock MIE firmware cannot do it. */\n"
    "#ifndef MIE_PROG_H\n#define MIE_PROG_H\n\n"
    "#define MIE_PROG_ORG  0x%04Xu\n"
    "#define MIE_PROG_LEN  %uu\n\n"
    "static const unsigned char mie_prog[MIE_PROG_LEN] = {\n%s\n};\n\n#endif\n"
    % (os.path.basename(src), org, len(blob), "\n".join(rows)))
print("%s: %d bytes, load at %04X, %d upload packets"
      % (out, len(blob), org, -(-len(blob) // 24)))
