/* Auto-generated stub for AUDIO=0 builds -- no PCM data embedded.
 * Keeps the CLIP_* enum and the audio_clips[] table so the report code
 * compiles unchanged; every clip is empty and aica_say() no-ops on a zero
 * sample count, so nothing is spoken and the ROM carries no speech at all.
 * Regenerate with: make AUDIO=0 (the Makefile writes this into audio_clips.h). */
#ifndef AUDIO_CLIPS_H
#define AUDIO_CLIPS_H

/* len is a sample count (ADPCM), matching the generated headers. */
typedef struct { const signed char *pcm; unsigned len; } audio_clip;

enum {
    CLIP_TESTS_DONE,
    CLIP_AUDIO_OK,
    CLIP_CPU_CACHE,
    CLIP_CPU_RAM,
    CLIP_DATA_BUS,
    CLIP_ADDR_BUS,
    CLIP_SOUND_RAM,
    CLIP_OK,
    CLIP_FAIL,
    CLIP_DEFECT,
    CLIP_NUM_1,
    CLIP_NUM_2,
    CLIP_NUM_3,
    CLIP_NUM_4,
    CLIP_NUM_5,
    CLIP_NUM_6,
    CLIP_NUM_7,
    CLIP_NUM_8,
    CLIP_IC_9,
    CLIP_IC_10,
    CLIP_IC_11,
    CLIP_IC_12,
    CLIP_IC_16,
    CLIP_IC_18,
    CLIP_IC_20,
    CLIP_IC_22,
    CLIP_IC_29,
    CLIP_IC_35,
    CLIP_IC_27,
    CLIP_BIOS,
    CLIP_VRAM,
    CLIP_SRAM,
    CLIP_RTC,
    CLIP_DIMM,
    CLIP_ABSENT,
    CLIP_PRESENT,
    CLIP_JVS,
    CLIP_NAOMI1,
    CLIP_NAOMI2,
    CLIP_BOARD_UNK,
    CLIP_VRAM_B,
    CLIP_ELAN,
    CLIP_EEPROM,
    CLIP_X76,
    CLIP_CART,
    CLIP_CPU_EXC,
    CLIP_IC_17S,
    CLIP_IC_19S,
    CLIP_IC_21S,
    CLIP_IC_23S,
    CLIP_IC_111,
    CLIP_IC_113,
    CLIP_IC_115,
    CLIP_IC_117,
    CLIP_IC_112S,
    CLIP_IC_114S,
    CLIP_IC_116S,
    CLIP_IC_118S,
    CLIP_IC_106,
    CLIP_IC_107,
    CLIP_IC_108S,
    CLIP_IC_109S,
    CLIP_JVS_IO,
    CLIP_LINE_D,
    CLIP_CUT_ON,
    CLIP_W_0,
    CLIP_W_1,
    CLIP_W_2,
    CLIP_W_3,
    CLIP_W_4,
    CLIP_W_5,
    CLIP_W_6,
    CLIP_W_7,
    CLIP_W_8,
    CLIP_W_9,
    CLIP_W_10,
    CLIP_W_11,
    CLIP_W_12,
    CLIP_W_13,
    CLIP_W_14,
    CLIP_W_15,
    CLIP_W_16,
    CLIP_W_17,
    CLIP_W_18,
    CLIP_W_19,
    CLIP_W_20,
    CLIP_W_30,
    CLIP_W_40,
    CLIP_W_50,
    CLIP_W_60,
    CLIP_W_AND_ONE,
    CLIP_COUNT
};

/* All entries {NULL, 0}: the zero initializer covers every element. */
static const audio_clip audio_clips[CLIP_COUNT] = { { 0, 0 } };

#endif
