/* =============================================================================
 * strings.h -- compile-time localized user-facing strings.
 *
 * Pick the language at build time with -DLANG_FR (French) or nothing / any
 * other value (English, the base language). One language is baked into each
 * ROM: NaomiDIAG_EN.bin / NaomiDIAG_FR.bin.
 *
 * Only operator-facing narrative + result labels are localized. Low-level
 * technical fragments (hex register dumps, "crc=", per-address fail dumps)
 * stay in English on purpose: they are diagnostic detail read by a
 * technician and are language-neutral.
 *
 * Also included by crt0.S (macros are plain string literals, cpp-safe).
 * ========================================================================== */
#ifndef STRINGS_H
#define STRINGS_H
#include "config.h"           /* SCIF_BAUD_STR */

#if defined(LANG_FR)
/* ------------------------------- French -------------------------------- */

/* boot (crt0.S) */
#define S_BANNER_A          "\r\n\r\n==== NAOMI DIAG ROM v"
#define S_BANNER_B          " (SH4/SCIF, boot sans RAM) ====\r\n"
#define S_BOOT_OCRAM_OK     "OC-RAM CPU (cache en RAM, 2x4Ko) ........ OK\r\n"
#define S_BOOT_OCRAM_KO     "OC-RAM CPU (cache en RAM) ........ ECHEC -- CPU inutilisable, arret\r\n"

/* result labels (SCIF + screen + drive the spoken clip) */
#define S_L_OCRAM           "OC-RAM CPU (SH-4 IC1)"
#define S_BEACON_HDR        "\nBalise de voies : ecritures 16 bits sur une seule puce a la fois.\n"\
                            "RAM CPU : sondez LDQM/UDQM. VRAM : sondez une broche DQ.\n"\
                            "La puce qui bouge est celle annoncee.\n"
#define S_BEACON_ON         "Balise -> "
#define S_BEACON_CPU1       "RAM CPU voie 1 : D0-D15 mot pair"
#define S_BEACON_CPU2       "RAM CPU voie 2 : D16-D31 mot pair"
#define S_BEACON_CPU3       "RAM CPU voie 3 : D0-D15 mot impair"
#define S_BEACON_CPU4       "RAM CPU voie 4 : D16-D31 mot impair"
#define S_BEACON_T0_1       "VRAM TEX0 voie 1"
#define S_BEACON_T0_2       "VRAM TEX0 voie 2"
#define S_BEACON_T0_3       "VRAM TEX0 voie 3"
#define S_BEACON_T0_4       "VRAM TEX0 voie 4"
#define S_BEACON_T1_1       "VRAM TEX1 voie 1"
#define S_BEACON_T1_2       "VRAM TEX1 voie 2"
#define S_BEACON_T1_3       "VRAM TEX1 voie 3"
#define S_BEACON_T1_4       "VRAM TEX1 voie 4"

#define S_INTERMITTENT      "  Defaut intermittent : vu a la verification, absent a la relecture.\n  La puce est nommee malgre tout : la parite du mot est conservee.\n"
#define S_L_BOARD_N1        "Carte : Naomi 1 (837-13544)"
#define S_L_BOARD_N2        "Carte : Naomi 2 (837-14009)"
#define S_L_BOARD_UNK       "Carte : INCONNUE (noms IC off)"
#define S_L_BIOS            "ROM BIOS (IC27) CRC32"
#define S_L_SDRAM_DBUS      "SDRAM bus de donnees"
#define S_L_SDRAM_ABUS      "SDRAM bus d'adresses"
#define S_BAD_ABITS         "  masque des etapes d'adresse en echec (pas un verdict sur les broches) : "
#define S_L_SDRAM_CELL      "SDRAM test cellules"
#define S_L_ARAM_DBUS       "RAM son bus de donnees"
#define S_L_ARAM_ABUS       "RAM son bus d'adresses"
#define S_G2_STALL          "  le bus G2 ne se vide jamais : resultat RAM son nul\n"
#define S_DIMM_MEM_ABORT    "  test SDRAM DIMM interrompu : aucun verdict\n"
#define S_SUITE_STOPPED     "\nSerie de tests interrompue.\n"
#define S_PH_STOPPED        " interrompue\n"
#define S_MIE_UP_OK         "  programme Z80 charge dans le MIE\n"
#define S_MIE_NO_ANSWER     "  le MIE ne repond pas au programme : boutons inactifs\n"
#define S_MIE_UP_FAIL       "  echec du chargement Z80 dans le MIE, paquet "
#define S_DIP_HDR           "  DIP SW1 : 1="
#define S_DIP_15K           "15 kHz"
#define S_DIP_31K           "31 kHz"
#define S_DIP_ON            "=ON"
#define S_DIP_OFF           "=OFF"
#define S_DIP_RAW           "   (port brut "
#define S_BTN_HDR           "  Boutons carte : TEST "
#define S_BTN_SVC           ", SERVICE "
#define S_BTN_UP            "relache"
#define S_BTN_DOWN          "APPUYE"
#define S_L_VRAM_T0_DBUS    "VRAM TEX0 bus de donnees"
#define S_L_VRAM_T0_ABUS    "VRAM TEX0 bus d'adresses"
#define S_L_VRAM_T1_DBUS    "VRAM TEX1 bus de donnees"
#define S_L_VRAM_T1_ABUS    "VRAM TEX1 bus d'adresses"
#define S_L_VRAM_B_DBUS     "VRAM PVR-B bus de donnees"
#define S_L_VRAM_B_ABUS     "VRAM PVR-B bus d'adresses"
#define S_L_ELAN_DBUS       "RAM Elan bus de donnees"
#define S_L_ELAN_ABUS       "RAM Elan bus d'adresses"
#define S_L_ARAM_CELL       "RAM son test cellules"
#define S_L_VRAM_TEX0       "VRAM TEX0"
#define S_L_VRAM_TEX0_IC    "VRAM TEX0 (IC16/18/20/22)"
#define S_L_VRAM_TEX1       "VRAM TEX1"
#define S_L_VRAM_TEX1_IC    "VRAM TEX1 (IC17S/19S/21S/23S)"
#define S_L_VRAM_B          "VRAM PVR-B (IC111 a IC118S)"
/* short labels for the progress bar: they get a " NN/10" pass suffix, so
 * they must stay well inside the screen width */
#define S_L_RELOC           "Boucles de test relogees en RAM"
#define S_L_RELOC_SCAN      "Blocs RAM CPU haute defectueux"
#define S_L_RELOC_CHK       "Integrite du code reloge en RAM"
#define S_RELOC_SUSPECT     "  La RAM portant le code de test s'est alteree en cours de route:\ntous les resultats ci-dessus sont douteux. Relancer avec une ROM RELOC=0.\n"
#define S_RELOC_ROM         "  RAM CPU inutilisable: boucles gardees en ROM (mode lent)\n"
#define S_RELOC_IN_RAM      " (RAM CPU, cache: mode rapide)\n"
#define S_RELOC_IN_ROM      " (EPROM, non cache: mode lent)\n"
#define S_P_BIOS            "Somme ROM BIOS"
#define S_P_ARAM            "RAM son"
#define S_P_VRAM            "VRAM"
#define S_P_SDRAM           "RAM CPU"
#define S_P_PASS            " passe "
#define S_P_CART_ID         "Identification cartouche"
#define S_P_CART_IC         "Cartouche"
#define S_P_CART_PINS       "Lignes cartouche"

#define S_L_ELAN            "RAM Elan (IC106/107/108S/109S)"
#define S_L_BACKSRAM        "NVRAM sauvegarde IC29 (intacte)"
#define S_L_RTC             "RTC (AICA, doit avancer)"
#define S_L_DIMM_ABSENT     "Carte DIMM : absente"
#define S_L_DIMM_PRESENT    "Carte DIMM : presente, mailbox"
#define S_L_MIE             "Bus Maple / MIE (JVS)"
#define S_L_MIE_NORESP      "Bus Maple / MIE : communication en echec"
#define S_L_MIE_SELFTEST    "Auto-test MIE (Z80 ROM+RAM)"
#define S_L_EEPROM_MIE      "EEPROM reglages (93C46 via MIE)"
#define S_L_EEPROM_GPIO     "EEPROM serie (IC31, 93C46)"
#define S_L_X76_ABSENT      "Securite cart. (X76F100) absente"
#define S_L_X76_PRESENT     "Securite cart. (X76F100) presente"
#define S_L_CART_ABSENT     "Cartouche : absente"
#define S_L_CART_SKIP       "SHA1 cartouche (RAM CPU HS)"
#define S_L_CART_UNKNOWN    "Cartouche : contenu inconnu"
#define S_L_CART_CONTENT    "Contenu cartouche (SHA1 par IC)"
#define S_L_CART_PRESENCE   "Presence des ROM cartouche"
#define S_L_CART_PINS       "Lignes de donnees cartouche"
#define S_L_AUDIO_QUICK     "RAM son zone clips (rapide)"
#define S_L_VIDEO_QUICK     "VRAM framebuffer (rapide)"
#define S_EXC_A             "\r\n*** EXCEPTION CPU : EXPEVT="
#define S_EXC_B             "  PC="
#define S_EXC_C             "  -- arret ***\r\n"
#define S_EXC_SCREEN        "EXCEPTION CPU "

/* status suffixes / words */
#define S_SUF_OK            " ........ OK\n"
#define S_SUF_FAIL          " ........ ECHEC\n"
#define S_SUF_SKIP          " ........ NON TESTE\n"
#define S_SUM_OK            ": OK\n"
#define S_SUM_FAIL          ": ECHEC\n"
#define S_SUM_SKIP          ": NON TESTE\n"
#define S_SCR_OK            "OK"
#define S_SCR_FAIL          "ECHEC"
#define S_SCR_SKIP          "NON TESTE"
#define S_SCR_SKIP_LEN      9
#define S_SCR_IC_BAD        "HS"
#define S_SCR_IC_ABS        "ABS"
#define S_SCR_IC_NOHASH     "--"
#define S_SCR_GAME          "Jeu : "
#define S_GOOD              " CORRECT\n"
#define S_BAD               " MAUVAIS\n"
#define S_DEFECTIVE         " DEFECTUEUX\n"

/* component group names (report_comps) */
#define S_CG_CPU            "RAM CPU"
#define S_ARAM_LINES        "  lignes de donnees fautives (D0-D15) : "
#define S_DIMM_HDR          "\nCarte DIMM : sonde et relecture double...\n"
#define S_DIMM_REGS         "  mailbox (cmd offl parl parh status) : "
#define S_L_DIMM_MEM        "DIMM : stabilite de lecture"
#define S_P_DIMM            "Memoire DIMM"
#define S_DIMM_MEM_HDR      "\n  test cellules DIMM (ecriture G1-DMA, DESTRUCTIF pour le jeu)...\n"
#define S_DIMM_MEM_PAT      "  motif "
#define S_DIMM_MEM_BLOCKS   "  blocs 32Ko ecrits/relus : "
#define S_DIMM_MEM_CRC      "  CRC ecrit/lu : "
#define S_DIMM_MEM_ERRS     "  erreurs : "
#define S_DIMM_MEM_FIRST    "  1re @ "
#define S_DIMM_MEM_EXPGOT   " attendu/lu "
#define S_DIMM_MEM_BADBITS  "  bits fautifs : "
#define S_DIMM_MEM_TIMEOUT  "  DMA sans reponse (DIMM non amorce ?)\n"
#define S_DIMM_SCRATCH_BAD  "  RAM tampon inutilisable, test cellules ignore\n"
#define S_L_DIMM_MEM_PAT    "DIMM : test cellules + CRC"
#define S_MENU_TITLE        "MENU OPERATEUR"
#define S_MENU_HINT         "TEST : choisir   SERVICE/START : lancer"
#define S_M_CPU             "Test RAM CPU en boucle"
#define S_M_VRAM            "Test RAM video en boucle"
#define S_M_ARAM            "Test RAM son en boucle"
#define S_M_DIMM            "Test complet de la carte DIMM"
#define S_M_GAME            "Integrite des flash du jeu (SHA1)"
#define S_M_FLASH           "Reflasher le DIMM"
#define S_NOT_IMPL          "\nNon implemente pour le moment.\n"
#define S_FW_HDR            "\nMise a jour firmware DIMM\n"
#define S_FW_IDING          "  identification de la flash DIMM (G1)...\n"
#define S_FW_ID             "  flash DIMM ID (fab/dev) : "
#define S_FW_NO_DIMM        "  aucune flash DIMM ne repond (carte presente et amorcee ?)\n"
#define S_FW_MENU           "  versions embarquees :\n    1  firmware 3.17\n    2  firmware 4.01\n    3  firmware 4.03 (CD-R)\n  touche 1/2/3 pour choisir, autre = annuler\n"
#define S_FW_SEL            "  version choisie : "
#define S_FW_PENDING        "  --> gravure NON armee (protocole chip-erase valide, en attente de\n      validation materielle avant d'ecrire). Rien n'a ete ecrit.\n"
#define S_FW_ABORT          "  annule.\n"
#define S_FW_V317           "Firmware 3.17"
#define S_FW_V401           "Firmware 4.01"
#define S_FW_V403           "Firmware 4.03 (CD-R)"
#define S_FW_CANCEL         "Annuler"
#define S_SCR_FW_ID         "Flash DIMM : "
#define S_SCR_FW_CANCEL     "Mise a jour DIMM annulee"
#define S_SCR_FW_SEL        "Version choisie : "
#define S_L_FW_NOID         "Flash DIMM (ne repond pas)"
#define S_L_FW_WRITE        "Gravure (pas encore armee)"
#define S_ABORTED           "\nTest interrompu.\n"
#define S_L_ABORTED         "Test interrompu par l'operateur"
#define S_LOOP_PASS         "passe "
#define S_LOOP_ERR          "  erreurs cumulees : "
#define S_LP_PASS           "Passe : "
#define S_LP_TIME           "Duree : "
#define S_LP_ERRS           "Erreurs cumulees : "
#define S_LP_FIRST          " err., 1re a la passe "
#define S_LP_HINT           "TEST ou START : arret"
#define S_LP_HINT_KEY       "Touche a (console) : arret"
#define S_WAIT_TEST         "\nAppuyez sur TEST ou SERVICE (carte) pour le menu operateur.\n"
#define S_IDLE_BANNER       "TEST ou START : menu operateur"
#define S_BUTTON_HINT       "TEST ou START : arret et menu operateur"
#define S_HELP              "\nMenu operateur -- touches :\n"\
                            "  h  cette aide (n'interrompt pas)\n"\
                            "  a  interrompre le test en cours (et une boucle, si les\n"\
                            "     boutons de la carte ne repondent pas)\n"\
                            "  c  test RAM CPU en boucle\n"\
                            "  v  test RAM video en boucle\n"\
                            "  s  test RAM son en boucle\n"\
                            "  d  test complet de la carte DIMM\n"\
                            "  g  integrite des flash du jeu (SHA1)\n"\
                            "  f  identifier la flash du DIMM (ecriture non armee)\n"\
                            "  j  test des entrees JVS (boutons, monnayeurs, analogiques)\n"\
                            "  m  mire video (barres, quadrillage, gris, purete...)\n"
#define S_M_JVS             "Test des entrees JVS"
#define S_M_PATTERN         "Mire video"
#define S_PAT_HINT          "TEST : suivante   SERVICE : quitter"
#define S_PAT_SERIAL        "\nMire video -- TEST ou une touche : suivante ; SERVICE, START, a ou q : quitter.\n"
#define S_PAT_NOSCREEN      "\nMire impossible : l'ecran n'est pas actif (VRAM non validee).\n"
#define S_PAT_END           "Fin de la mire.\n"
#define S_PAT_0             "barres de couleur"
#define S_PAT_1             "quadrillage (geometrie, convergence)"
#define S_PAT_2             "echelle de gris, 16 pas"
#define S_PAT_3             "rampes rouge, vert, bleu, blanc (bits du DAC)"
#define S_PAT_4             "blanc (purete)"
#define S_PAT_5             "rouge (purete)"
#define S_PAT_6             "vert (purete)"
#define S_PAT_7             "bleu (purete)"
#define S_PAT_8             "noir"
#define S_PAT_9             "damier d'un pixel (bande passante)"
#define S_L_JVS_READY       "Carte I/O JVS : presente"
#define S_L_JVS_ABSENT      "Carte I/O JVS : absente"
#define S_L_JVS_ERROR       "Carte I/O JVS : dialogue en echec"
#define S_L_JVS_STUCK       "Maitre JVS du MIE sans reponse"
#define S_JVS_HDR           "\nJVS : recherche d'une carte I/O...\n"
#define S_JVS_SKIP          "\nTest JVS ignore : programme MIE absent.\n"
#define S_JVS_ID            "  Identifiant : "
#define S_JVS_REV           "  Revisions commande / JVS / communication : "
#define S_JVS_FEAT          "  Entrees : "
#define S_JVS_PLAYERS       " joueur(s) x "
#define S_JVS_BUTTONS       " contacts, "
#define S_JVS_COINS         " monnayeur(s), "
#define S_JVS_ANALOG        " voie(s) analogique(s) de "
#define S_JVS_BITS          " bits\n"
#define S_JVS_SENSE         "  Ligne SENSE (port 91h) : "
#define S_JVS_ERRINFO       "  Derniere erreur : code "
#define S_JVS_ERRSTEP       ", etape "
#define S_JVS_ERRCODES      "  (1 delai, 2 somme, 3 statut, 4 rapport ; etapes 2 adresse, 3 ident., 7 fonctions, 8 lecture)\n"
#define S_JT_TITLE          "TEST DES ENTREES JVS"
#define S_JT_QUIT           "SERVICE (carte) : quitter"
#define S_JT_BOARD          "CARTE"
#define S_JT_BOARD_SER      "  TEST carte : "
#define S_JT_WAIT           "Recherche de la carte I/O..."
#define S_JT_NONE           "Aucune carte I/O JVS ne repond"
#define S_JT_ERR            "Dialogue JVS en echec, nouvel essai..."
#define S_JT_SYS            "SYS"
#define S_JT_PLAYER         "J"
#define S_JT_COINS          "PIECES"
#define S_JT_ANA            "ANA"
#define S_JT_DIR_U          "H"
#define S_JT_DIR_D          "B"
#define S_JT_DIR_L          "G"
#define S_JT_DIR_R          "D"
#define S_JT_SERIAL         "\nTest des entrees JVS -- SERVICE carte ou une touche pour quitter.\n"
#define S_JT_END            "Fin du test des entrees JVS.\n"
#define S_CG_SOUND          "RAM son"
#define S_CG_SRAM           "NVRAM"
#define S_CG_PVRB           "VRAM PVR-B"
#define S_CG_ELAN           "RAM Elan"

/* phase headers / narrative */
#define S_ETA               "  Temps restant estime : "
#define S_SCIF_UP           "Console SCIF active, " SCIF_BAUD_STR " 8N1\n"
#define S_SDRAM_INIT        "\nInit SDRAM (valeurs BSC du BIOS d'origine)...\n"
#define S_SDRAM_SIZE        "Taille SDRAM detectee : "
#define S_MB                " Mo\n"
#define S_QUICK             "Build QUICK : test du 1er Mo seulement\n"
#define S_PASS              "passe "
#define S_PH_0101           "0101 : "
#define S_PH_1010           "1010 : "
/* the CRC is only there when CFG_RAM_CRC turns it on */
#if CFG_RAM_CRC
#define S_PH_PRNG           "pseudo-aleatoire + CRC : "
#else
#define S_PH_PRNG           "pseudo-aleatoire : "
#endif
#define S_AICA_HDR          "\nAICA : ARM7 en reset, test RAM son (8 Mo, bus G2)...\n"
#define S_PVR_HDR           "\nPVR : activation controleur VRAM, test RAM texture...\n"
#define S_SDRAM_HDR         "\nSDRAM : test RAM CPU, bus et cellules...\n"
#define S_N2_HDR            "\nNaomi 2 : test VRAM du PVR esclave et RAM Elan...\n"
#define S_N2_SKIP           "\nMemoires Naomi 2 non testees : carte non identifiee comme Naomi 2.\n"
#define S_L_PVRB_ACCESS     "Acces PVR-B"
#define S_L_PVRA_REFERENCE  "Reference PVR-A (PVR-B indetermine)"
#define S_VRAM_BIOS_IC      "  Voie associee par le BIOS SEGA (puce ou connexions a verifier) :"
#define S_VRAM_SCAN         "  Erreur detectee, localisation VRAM"
#define S_SDRAM_SCAN        "  Erreur detectee, localisation RAM CPU"
#define S_SDRAM_SCAN_BAR    "Localisation RAM CPU"
#define S_VRAM_SCAN_BAR     "Localisation VRAM"
#define S_CUT_PRE           "Ligne D"
#define S_CUT_MID           " coupee sur "
#define S_CUT_SERIAL        "  Ligne coupee D"
#define S_CUT_HIGH          "lue toujours a 1"
#define S_CUT_LOW           "lue toujours a 0"
#define S_CUT_FLOAT         "flottante"
#define S_ADDR_PRE          "Adresse A"
#define S_BANK_PRE          "Adresse BA"
#define S_ABIT_PRE          "Bit d'adresse "
#define S_ABIT_MID          " fautif sur "
#define S_ADDR_ALL          " coupee, 4 puces"
#define S_ADDR_CHIPS        " puces"
#define S_ADDR_SERIAL       "  Ligne d'adresse coupee : SDRAM "
#define S_ADDR_BITS         ", bits d'adresse CPU :"
#define S_ADDR_COL          " (colonne)"
#define S_ADDR_ROW          " (ligne)"
#define S_ADDR_BANK         " (banque)"
#define S_ADDR_DEAD         "  Une puce se replie sur trop de bits d'adresse : puce ou voie de donnees, pas des lignes d'adresse.\n"
#define S_VRAM_UNLOCATED    "  Erreur non relocalisee : plusieurs IC candidats dans la plage testee.\n"
#define S_VRAM_SUSPECT      " : voie suspecte (puce ou connexions)\n"
#define S_VRAM_DIAG        "  Diagnostic VRAM : cellules puis paires d'adresses.\n  Bits CPU uniquement : correspondance broches RAM non etablie.\n"
#define S_PVRB_SKIP         "  VRAM PVR-B non testee, acces non valide.\n  Aucun verdict sur les puces RAM. Code acces : "
#define S_ELAN_SKIP         "  RAM Elan non testee : l'Elan ne repond pas (voir le code ci-dessus).\n"
#define S_PVRB_SILENT       "  La VRAM du PVR-B ne garde aucune valeur ecrite : puces, controleur\n  ou initialisation. Pas de verdict par puce.\n"
#define S_SCREEN_ONLINE     "Ecran actif : rapport affiche sur la sortie VGA.\n"
#define S_SCREEN_TEX1       "  Image deplacee sur TEX1 : la zone image de TEX0 est defaillante.\n"
#define S_L_VIDEO_QUICK_T1  "VRAM framebuffer TEX1 (secours)"
#define S_PERIPH_HDR        "\nNVRAM sauvegarde (IC29, non destructif) + RTC AICA (IC33)...\n"
#define S_RTC_DATE          "  Date RTC : "
#define S_RTC_TICK          " (avance)\n"
#define S_RTC_STUCK         " (figee : aucune avance sur deux mesures)\n"
#define S_RTC_IRREG         " (irreguliere : immobile puis repartie)\n"
#define S_RTC_JUMP          " (saut aberrant entre deux lectures)\n"
#define S_RTC_READS         "  Lectures RTC : "
#define S_L_RTC_DATE        "Date RTC (2026 ou apres)"
#define S_RTC_DATE_BAD      "  Date anterieure a 2026 : pile HS ou horloge jamais reglee.\n"
#define S_MAPLE_SKIP        "\nTest Maple/MIE ignore (RAM principale inutilisable).\n"
#define S_EEPROM_SKIP       "\nTest EEPROM reglages ignore (pas de MIE).\n"
#define S_EEPROM_MIE_NOTE   "  le programme MIE ne rend pas l'EEPROM\n"
#define S_CART_HDR          "\nEn-tete cartouche : \""
#define S_IDENTIFYING       "Identification"
#define S_CART_DMA_ON       "Lecture cartouche : DMA G1, double tampon\n"
#define S_CART_DMA_OFF      "Lecture cartouche : port PIO (DMA G1 non conforme)\n"
#define S_CART_8K_DMA       "  8 Ko par DMA G1 : "
#define S_CART_8K_PIO       " us, par le port PIO : "
#define S_CART_8K_US        " us\n"
#define S_CART_DMA_LOST     " [DMA G1 muet, suite par le port PIO] "
#define S_CART_RECHECK      " relecture par le port PIO"
#define S_CART_DMA_WRONG    " [le DMA G1 lisait faux : port PIO desormais] "
#define S_CART_NORELOC      "Contenu cartouche non verifie : aucune RAM CPU valide pour\n"\
                            "  reloger le calcul SHA-1 (depuis l'EPROM : ~9 s par Mo,\n"\
                            "  20 min pour un jeu moyen). Lignes de donnees seules.\n"
#define S_CART_NOTINDB      "  cartouche absente de la base (inconnue ou 1ere IC corrompue)\n"
#define S_IDENTIFIED        "  identifiee : "
#define S_CART_NDEF_A       "  "
#define S_CART_NDEF_B       " IC de cartouche DEFECTUEUSE(S) (voir liste ci-dessus)\n"
#define S_NO_RESPONSE       " AUCUNE REPONSE (absente ou mal enfichee)\n"
#define S_PRESENT_ONLY      " presente (hachage ignore)\n"
#define S_ROMSET_A          "  jeu de ROM : "
#define S_ROMSET_B          " / "
#define S_ROMSET_C          " puces presentes\n"
#define S_ALIAS_A           "  <-- MEME CONTENU QUE "
#define S_ALIAS_B           " (puce absente, miroir d'adresses)\n"
#define S_CART_NMISS_A      "  "
#define S_CART_NMISS_B      " IC de cartouche NE REPONDENT PAS\n"
#define S_PINS_HDR          "\nStatistiques par ligne de donnees (2 lectures comparees) :\n"
#define S_PINS_SAMPLED      "  mots echantillonnes : "
#define S_PIN               "  D"
#define S_PIN_ONES          " : "
#define S_PIN_PCT           "% de 1"
#define S_PIN_STUCK         "  <-- LIGNE FIGEE"
#define S_PIN_FLAKY         "  <-- INSTABLE, ecarts : "
#define S_PINS_OK           "  toutes les lignes stables et actives\n"
#define S_AUDIO_ONLINE      "Audio actif : relecture des resultats acquis sur haut-parleur...\n"
#define S_SUMMARY           "\n==== RESUME ====\n"
#define S_MAINRAM_OK        "RAM principale utilisable.\n"
#define S_MAINRAM_KO        "RAM principale INUTILISABLE -> mode OC-RAM uniquement.\n"
#define S_ARAM_OK_MSG       "RAM son utilisable, rapports audio actifs.\n"
#define S_VRAM_OK_MSG       "VRAM utilisable, rapport a l'ecran actif.\n"
#define S_COMPLETE          "\n*** DIAGNOSTIC TERMINE ***\n"

#else
/* ------------------------------- English (base) ------------------------ */

#define S_BANNER_A          "\r\n\r\n==== NAOMI DIAG ROM v"
#define S_BANNER_B          " (SH4/SCIF, no-RAM boot) ====\r\n"
#define S_BOOT_OCRAM_OK     "CPU OC-RAM (cache as RAM, 2x4KB) ........ OK\r\n"
#define S_BOOT_OCRAM_KO     "CPU OC-RAM (cache as RAM) ........ FAIL -- CPU unusable, halting\r\n"

#define S_L_OCRAM           "CPU OC-RAM (SH-4 IC1)"
#define S_BEACON_HDR        "\nLane beacon: 16-bit writes hitting one chip at a time.\n"\
                            "CPU RAM: probe LDQM/UDQM. VRAM: probe a DQ pin.\n"\
                            "The chip that moves is the one named.\n"
#define S_BEACON_ON         "Beacon -> "
#define S_BEACON_CPU1       "CPU RAM lane 1: D0-D15 even word"
#define S_BEACON_CPU2       "CPU RAM lane 2: D16-D31 even word"
#define S_BEACON_CPU3       "CPU RAM lane 3: D0-D15 odd word"
#define S_BEACON_CPU4       "CPU RAM lane 4: D16-D31 odd word"
#define S_BEACON_T0_1       "VRAM TEX0 lane 1"
#define S_BEACON_T0_2       "VRAM TEX0 lane 2"
#define S_BEACON_T0_3       "VRAM TEX0 lane 3"
#define S_BEACON_T0_4       "VRAM TEX0 lane 4"
#define S_BEACON_T1_1       "VRAM TEX1 lane 1"
#define S_BEACON_T1_2       "VRAM TEX1 lane 2"
#define S_BEACON_T1_3       "VRAM TEX1 lane 3"
#define S_BEACON_T1_4       "VRAM TEX1 lane 4"

#define S_INTERMITTENT      "  Intermittent fault: seen while verifying, gone on re-scan.\n  The chip is still named: the word parity was kept.\n"
#define S_L_BOARD_N1        "Board: Naomi 1 (837-13544)"
#define S_L_BOARD_N2        "Board: Naomi 2 (837-14009)"
#define S_L_BOARD_UNK       "Board: UNKNOWN - IC names off"
#define S_L_BIOS            "BIOS ROM (IC27) CRC32"
#define S_L_SDRAM_DBUS      "SDRAM data bus"
#define S_L_SDRAM_ABUS      "SDRAM address bus"
#define S_BAD_ABITS         "  failing address-test steps mask (not a pin verdict): "
#define S_L_SDRAM_CELL      "SDRAM cell test"
#define S_L_ARAM_DBUS       "Sound RAM data bus"
#define S_L_ARAM_ABUS       "Sound RAM address bus"
#define S_G2_STALL          "  G2 bus never went idle: sound RAM result is void\n"
#define S_DIMM_MEM_ABORT    "  DIMM SDRAM test aborted: no verdict\n"
#define S_SUITE_STOPPED     "\nTest suite interrupted.\n"
#define S_PH_STOPPED        " interrupted\n"
#define S_MIE_UP_OK         "  Z80 program loaded into the MIE\n"
#define S_MIE_NO_ANSWER     "  the MIE does not answer it: buttons stay inactive\n"
#define S_MIE_UP_FAIL       "  MIE Z80 upload failed at packet "
#define S_DIP_HDR           "  DIP SW1: 1="
#define S_DIP_15K           "15 kHz"
#define S_DIP_31K           "31 kHz"
#define S_DIP_ON            "=ON"
#define S_DIP_OFF           "=OFF"
#define S_DIP_RAW           "   (raw port "
#define S_BTN_HDR           "  Board buttons: TEST "
#define S_BTN_SVC           ", SERVICE "
#define S_BTN_UP            "released"
#define S_BTN_DOWN          "PRESSED"
#define S_L_VRAM_T0_DBUS    "VRAM TEX0 data bus"
#define S_L_VRAM_T0_ABUS    "VRAM TEX0 address bus"
#define S_L_VRAM_T1_DBUS    "VRAM TEX1 data bus"
#define S_L_VRAM_T1_ABUS    "VRAM TEX1 address bus"
#define S_L_VRAM_B_DBUS     "VRAM PVR-B data bus"
#define S_L_VRAM_B_ABUS     "VRAM PVR-B address bus"
#define S_L_ELAN_DBUS       "Elan RAM data bus"
#define S_L_ELAN_ABUS       "Elan RAM address bus"
#define S_L_ARAM_CELL       "Sound RAM cell test"
#define S_L_VRAM_TEX0       "VRAM TEX0"
#define S_L_VRAM_TEX0_IC    "VRAM TEX0 (IC16/18/20/22)"
#define S_L_VRAM_TEX1       "VRAM TEX1"
#define S_L_VRAM_TEX1_IC    "VRAM TEX1 (IC17S/19S/21S/23S)"
#define S_L_VRAM_B          "VRAM PVR-B (IC111 to IC118S)"
/* short labels for the progress bar: they get a " NN/10" pass suffix, so
 * they must stay well inside the screen width */
#define S_L_RELOC           "Test loops relocated to CPU RAM"
#define S_L_RELOC_SCAN      "Bad blocks at top of CPU RAM"
#define S_L_RELOC_CHK       "Relocated code integrity"
#define S_RELOC_SUSPECT     "  The RAM holding the test code changed under us: every result\nabove is suspect. Re-run with a RELOC=0 ROM.\n"
#define S_RELOC_ROM         "  CPU RAM unusable: loops kept in ROM (slow mode)\n"
#define S_RELOC_IN_RAM      " (CPU RAM, cached: fast mode)\n"
#define S_RELOC_IN_ROM      " (EPROM, uncached: slow mode)\n"
#define S_P_BIOS            "BIOS ROM checksum"
#define S_P_ARAM            "Sound RAM"
#define S_P_VRAM            "VRAM"
#define S_P_SDRAM           "CPU RAM"
#define S_P_PASS            " pass "
#define S_P_CART_ID         "Cartridge ID"
#define S_P_CART_IC         "Cartridge"
#define S_P_CART_PINS       "Cartridge lines"

#define S_L_ELAN            "Elan RAM (IC106/107/108S/109S)"
#define S_L_BACKSRAM        "Backup NVRAM IC29 (kept intact)"
#define S_L_RTC             "RTC (AICA, must tick)"
#define S_L_DIMM_ABSENT     "DIMM board: not present"
#define S_L_DIMM_PRESENT    "DIMM board: present, mailbox"
#define S_L_MIE             "Maple bus / MIE (JVS)"
#define S_L_MIE_NORESP      "Maple bus / MIE: communication failed"
#define S_L_MIE_SELFTEST    "MIE self-test (Z80 ROM+RAM)"
#define S_L_EEPROM_MIE      "Settings EEPROM (93C46 via MIE)"
#define S_L_EEPROM_GPIO     "Serial EEPROM (IC31, 93C46)"
#define S_L_X76_ABSENT      "Cart security (X76F100): absent"
#define S_L_X76_PRESENT     "Cart security (X76F100): present"
#define S_L_CART_ABSENT     "Cartridge: not present"
#define S_L_CART_SKIP       "Cart SHA1 (CPU RAM bad)"
#define S_L_CART_UNKNOWN    "Cartridge: unknown content"
#define S_L_CART_CONTENT    "Cartridge content (SHA1 per IC)"
#define S_L_CART_PRESENCE   "Cartridge ROM presence"
#define S_L_CART_PINS       "Cartridge data lines"
#define S_L_AUDIO_QUICK     "Sound RAM clip zone quick check"
#define S_L_VIDEO_QUICK     "VRAM framebuffer quick check"
#define S_EXC_A             "\r\n*** CPU EXCEPTION: EXPEVT="
#define S_EXC_B             "  PC="
#define S_EXC_C             "  -- halted ***\r\n"
#define S_EXC_SCREEN        "CPU EXCEPTION "

#define S_SUF_OK            " ........ OK\n"
#define S_SUF_FAIL          " ........ FAIL\n"
#define S_SUF_SKIP          " ........ NOT TESTED\n"
#define S_SUM_OK            ": OK\n"
#define S_SUM_FAIL          ": FAIL\n"
#define S_SUM_SKIP          ": NOT TESTED\n"
#define S_SCR_OK            "OK"
#define S_SCR_FAIL          "FAIL"
#define S_SCR_SKIP          "NOT TESTED"
#define S_SCR_SKIP_LEN      10
#define S_SCR_IC_BAD        "BAD"
#define S_SCR_IC_ABS        "ABS"
#define S_SCR_IC_NOHASH     "--"
#define S_SCR_GAME          "Game: "
#define S_GOOD              " GOOD\n"
#define S_BAD               " BAD\n"
#define S_DEFECTIVE         " DEFECTIVE\n"

#define S_CG_CPU            "CPU RAM"
#define S_ARAM_LINES        "  bad data lines (D0-D15): "
#define S_DIMM_HDR          "\nDIMM board: probe and double read...\n"
#define S_DIMM_REGS         "  mailbox (cmd offl parl parh status): "
#define S_L_DIMM_MEM        "DIMM: double read (stability)"
#define S_P_DIMM            "DIMM memory"
#define S_DIMM_MEM_HDR      "\n  DIMM cell test (G1-DMA write, DESTRUCTIVE to the game)...\n"
#define S_DIMM_MEM_PAT      "  pattern "
#define S_DIMM_MEM_BLOCKS   "  32KB blocks written/read: "
#define S_DIMM_MEM_CRC      "  CRC written/read: "
#define S_DIMM_MEM_ERRS     "  errors: "
#define S_DIMM_MEM_FIRST    "  first @ "
#define S_DIMM_MEM_EXPGOT   " exp/got "
#define S_DIMM_MEM_BADBITS  "  bad bits: "
#define S_DIMM_MEM_TIMEOUT  "  DMA no response (DIMM not booted?)\n"
#define S_DIMM_SCRATCH_BAD  "  scratch RAM unusable, cell test skipped\n"
#define S_L_DIMM_MEM_PAT    "DIMM: cell test + CRC"
#define S_MENU_TITLE        "OPERATOR MENU"
#define S_MENU_HINT         "TEST: select   SERVICE/START: run"
#define S_M_CPU             "CPU RAM test, looping"
#define S_M_VRAM            "Video RAM test, looping"
#define S_M_ARAM            "Sound RAM test, looping"
#define S_M_DIMM            "Full DIMM board test"
#define S_M_GAME            "Game flash integrity (SHA1)"
#define S_M_FLASH           "Reflash the DIMM"
#define S_NOT_IMPL          "\nNot implemented yet.\n"
#define S_FW_HDR            "\nDIMM firmware update\n"
#define S_FW_IDING         "  identifying the DIMM flash (G1)...\n"
#define S_FW_ID            "  DIMM flash ID (mfr/dev): "
#define S_FW_NO_DIMM       "  no DIMM flash responding (board present and booted?)\n"
#define S_FW_MENU          "  embedded versions:\n    1  firmware 3.17\n    2  firmware 4.01\n    3  firmware 4.03 (CD-R)\n  press 1/2/3 to choose, anything else = cancel\n"
#define S_FW_SEL           "  selected version: "
#define S_FW_PENDING       "  --> flash write NOT armed (chip-erase protocol validated, awaiting\n      hardware validation before writing). Nothing was written.\n"
#define S_FW_ABORT         "  cancelled.\n"
#define S_FW_V317           "Firmware 3.17"
#define S_FW_V401           "Firmware 4.01"
#define S_FW_V403           "Firmware 4.03 (CD-R)"
#define S_FW_CANCEL         "Cancel"
#define S_SCR_FW_ID         "DIMM flash: "
#define S_SCR_FW_CANCEL     "DIMM update cancelled"
#define S_SCR_FW_SEL        "Selected version: "
#define S_L_FW_NOID         "DIMM flash (no answer)"
#define S_L_FW_WRITE        "Flash write (not armed yet)"
#define S_ABORTED           "\nTest interrupted.\n"
#define S_L_ABORTED         "Test interrupted by the operator"
#define S_LOOP_PASS         "pass "
#define S_LOOP_ERR          "  errors so far: "
#define S_LP_PASS           "Pass: "
#define S_LP_TIME           "Time: "
#define S_LP_ERRS           "Errors so far: "
#define S_LP_FIRST          " err., first on pass "
#define S_LP_HINT           "TEST or START: stop"
#define S_LP_HINT_KEY       "Key a (console): stop"
#define S_WAIT_TEST         "\nPress TEST or SERVICE (on the board) for the operator menu.\n"
#define S_IDLE_BANNER       "TEST or START: operator menu"
#define S_BUTTON_HINT       "TEST or START: stop and operator menu"
#define S_HELP              "\nOperator menu -- keys:\n"\
                            "  h  this help (does not interrupt)\n"\
                            "  a  abort the running test (and a loop, when the board\n"\
                            "     buttons do not answer)\n"\
                            "  c  CPU RAM test, looping\n"\
                            "  v  video RAM test, looping\n"\
                            "  s  sound RAM test, looping\n"\
                            "  d  full DIMM board test\n"\
                            "  g  game flash integrity (SHA1)\n"\
                            "  f  identify the DIMM flash (writing not armed)\n"\
                            "  j  JVS input test (buttons, coin slots, analog)\n"\
                            "  m  video test pattern (bars, crosshatch, grey, purity...)\n"
#define S_M_JVS             "JVS input test"
#define S_M_PATTERN         "Video test pattern"
#define S_PAT_HINT          "TEST: next   SERVICE: quit"
#define S_PAT_SERIAL        "\nVideo test pattern -- TEST or a key: next; SERVICE, START, a or q: quit.\n"
#define S_PAT_NOSCREEN      "\nNo test pattern: the screen is not active (VRAM not validated).\n"
#define S_PAT_END           "Test pattern over.\n"
#define S_PAT_0             "colour bars"
#define S_PAT_1             "crosshatch (geometry, convergence)"
#define S_PAT_2             "grey scale, 16 steps"
#define S_PAT_3             "red, green, blue, white ramps (DAC bits)"
#define S_PAT_4             "white (purity)"
#define S_PAT_5             "red (purity)"
#define S_PAT_6             "green (purity)"
#define S_PAT_7             "blue (purity)"
#define S_PAT_8             "black"
#define S_PAT_9             "one-pixel checkerboard (bandwidth)"
#define S_L_JVS_READY       "JVS I/O board: present"
#define S_L_JVS_ABSENT      "JVS I/O board: not present"
#define S_L_JVS_ERROR       "JVS I/O board: exchange failing"
#define S_L_JVS_STUCK       "MIE JVS master not answering"
#define S_JVS_HDR           "\nJVS: looking for an I/O board...\n"
#define S_JVS_SKIP          "\nJVS test skipped: no MIE program.\n"
#define S_JVS_ID            "  Identification: "
#define S_JVS_REV           "  Revisions command / JVS / communication: "
#define S_JVS_FEAT          "  Inputs: "
#define S_JVS_PLAYERS       " player(s) x "
#define S_JVS_BUTTONS       " switches, "
#define S_JVS_COINS         " coin slot(s), "
#define S_JVS_ANALOG        " analog channel(s) of "
#define S_JVS_BITS          " bits\n"
#define S_JVS_SENSE         "  SENSE line (port 91h): "
#define S_JVS_ERRINFO       "  Last error: code "
#define S_JVS_ERRSTEP       ", step "
#define S_JVS_ERRCODES      "  (1 timeout, 2 checksum, 3 status, 4 report; steps 2 address, 3 ident, 7 features, 8 read)\n"
#define S_JT_TITLE          "JVS INPUT TEST"
#define S_JT_QUIT           "SERVICE (board): quit"
#define S_JT_BOARD          "BOARD"
#define S_JT_BOARD_SER      "  Board TEST: "
#define S_JT_WAIT           "Looking for the I/O board..."
#define S_JT_NONE           "No JVS I/O board answers"
#define S_JT_ERR            "JVS exchange failing, retrying..."
#define S_JT_SYS            "SYS"
#define S_JT_PLAYER         "P"
#define S_JT_COINS          "COINS"
#define S_JT_ANA            "ANA"
#define S_JT_DIR_U          "U"
#define S_JT_DIR_D          "D"
#define S_JT_DIR_L          "L"
#define S_JT_DIR_R          "R"
#define S_JT_SERIAL         "\nJVS input test -- board SERVICE or any key to quit.\n"
#define S_JT_END            "JVS input test over.\n"
#define S_CG_SOUND          "SOUND RAM"
#define S_CG_SRAM           "SRAM"
#define S_CG_PVRB           "PVR-B VRAM"
#define S_CG_ELAN           "ELAN RAM"

#define S_ETA               "  Estimated time left: "
#define S_SCIF_UP           "SCIF console up, " SCIF_BAUD_STR " 8N1\n"
#define S_SDRAM_INIT        "\nSDRAM init (BSC values from original BIOS)...\n"
#define S_SDRAM_SIZE        "SDRAM detected size: "
#define S_MB                " MB\n"
#define S_QUICK             "QUICK build: testing first 1MB only\n"
#define S_PASS              "pass "
#define S_PH_0101           "0101: "
#define S_PH_1010           "1010: "
#if CFG_RAM_CRC
#define S_PH_PRNG           "pseudo-random + CRC: "
#else
#define S_PH_PRNG           "pseudo-random: "
#endif
#define S_AICA_HDR          "\nAICA: ARM7 held in reset, testing sound RAM (8MB, G2 bus)...\n"
#define S_PVR_HDR           "\nPVR: enabling VRAM controller, testing texture RAM...\n"
#define S_SDRAM_HDR         "\nSDRAM: testing CPU RAM, bus and cells...\n"
#define S_N2_HDR            "\nNaomi 2: testing slave PVR VRAM and Elan RAM...\n"
#define S_N2_SKIP           "\nNaomi 2 memories not tested: board not identified as Naomi 2.\n"
#define S_L_PVRB_ACCESS     "PVR-B access"
#define S_L_PVRA_REFERENCE  "PVR-A reference (PVR-B inconclusive)"
#define S_VRAM_BIOS_IC      "  SEGA BIOS lane assignment (check chip and connections):"
#define S_VRAM_SCAN         "  Error detected, locating VRAM failures"
#define S_SDRAM_SCAN        "  Error detected, locating CPU RAM failures"
#define S_SDRAM_SCAN_BAR    "Locating CPU RAM errors"
#define S_VRAM_SCAN_BAR     "Locating VRAM errors"
#define S_CUT_PRE           "Line D"
#define S_CUT_MID           " cut on "
#define S_CUT_SERIAL        "  Cut line D"
#define S_CUT_HIGH          "always reads 1"
#define S_CUT_LOW           "always reads 0"
#define S_CUT_FLOAT         "floating"
#define S_ADDR_PRE          "Address A"
#define S_BANK_PRE          "Address BA"
#define S_ABIT_PRE          "Address bit "
#define S_ABIT_MID          " faulty on "
#define S_ADDR_ALL          " cut, all 4 chips"
#define S_ADDR_CHIPS        " chips"
#define S_ADDR_SERIAL       "  Cut address line: SDRAM "
#define S_ADDR_BITS         ", CPU address bits:"
#define S_ADDR_COL          " (column)"
#define S_ADDR_ROW          " (row)"
#define S_ADDR_BANK         " (bank)"
#define S_ADDR_DEAD         "  A chip aliases on too many address bits: the chip or its data lane, not address lines.\n"
#define S_VRAM_UNLOCATED    "  Error not relocated: multiple IC candidates within the tested range.\n"
#define S_VRAM_SUSPECT      " : suspect lane (chip or connections)\n"
#define S_VRAM_DIAG        "  VRAM diagnosis: cells followed by address pairs.\n  CPU bits only: RAM address-pin mapping is not established.\n"
#define S_PVRB_SKIP         "  PVR-B VRAM not tested: access not qualified.\n  No RAM-chip verdict. Access code: "
#define S_ELAN_SKIP         "  Elan RAM not tested: the Elan does not answer (see the code above).\n"
#define S_PVRB_SILENT       "  PVR-B VRAM holds nothing written to it: chips, controller or\n  initialisation. No per-chip verdict.\n"
#define S_SCREEN_ONLINE     "Screen online: report displayed on VGA output.\n"
#define S_SCREEN_TEX1       "  Image moved to TEX1: TEX0's image area is bad.\n"
#define S_L_VIDEO_QUICK_T1  "VRAM framebuffer TEX1 (fallback)"
#define S_PERIPH_HDR        "\nBackup NVRAM (IC29, non-destructive) + AICA RTC (IC33)...\n"
#define S_RTC_DATE          "  RTC date: "
#define S_RTC_TICK          " (ticking)\n"
#define S_RTC_STUCK         " (stopped: no progress over two measurements)\n"
#define S_RTC_IRREG         " (irregular: still, then moving again)\n"
#define S_RTC_JUMP          " (implausible jump between two reads)\n"
#define S_RTC_READS         "  RTC reads: "
#define S_L_RTC_DATE        "RTC date (2026 or later)"
#define S_RTC_DATE_BAD      "  Date before 2026: flat battery, or the clock was never set.\n"
#define S_MAPLE_SKIP        "\nMaple/MIE test skipped (main RAM unusable).\n"
#define S_EEPROM_SKIP       "\nSettings EEPROM test skipped (no MIE).\n"
#define S_EEPROM_MIE_NOTE   "  the MIE program did not return the EEPROM\n"
#define S_CART_HDR          "\nCartridge header: \""
#define S_IDENTIFYING       "Identifying"
#define S_CART_DMA_ON       "Cartridge read: G1 DMA, double-buffered\n"
#define S_CART_DMA_OFF      "Cartridge read: PIO port (G1 DMA check failed)\n"
#define S_CART_8K_DMA       "  8 KB by G1 DMA: "
#define S_CART_8K_PIO       " us, by the PIO port: "
#define S_CART_8K_US        " us\n"
#define S_CART_DMA_LOST     " [G1 DMA silent, PIO port from here] "
#define S_CART_RECHECK      " re-read through the PIO port"
#define S_CART_DMA_WRONG    " [G1 DMA read wrong: PIO port from now on] "
#define S_CART_NORELOC      "Cartridge content not checked: no good CPU RAM to relocate\n"\
                            "  the SHA-1 rounds into (from the EPROM: ~9 s per MB,\n"\
                            "  20 min for a typical game). Data lines only.\n"
#define S_CART_NOTINDB      "  cartridge not in database (unknown or corrupted first IC)\n"
#define S_IDENTIFIED        "  identified: "
#define S_CART_NDEF_A       "  "
#define S_CART_NDEF_B       " cartridge IC(s) DEFECTIVE (see list above)\n"
#define S_NO_RESPONSE       " NO RESPONSE (missing or not seated)\n"
#define S_PRESENT_ONLY      " present (hash skipped)\n"
#define S_ROMSET_A          "  ROM set: "
#define S_ROMSET_B          " / "
#define S_ROMSET_C          " chips present\n"
#define S_ALIAS_A           "  <-- SAME CONTENT AS "
#define S_ALIAS_B           " (chip missing, address aliasing)\n"
#define S_CART_NMISS_A      "  "
#define S_CART_NMISS_B      " cartridge IC(s) NOT RESPONDING\n"
#define S_PINS_HDR          "\nPer-data-line statistics (two reads compared):\n"
#define S_PINS_SAMPLED      "  words sampled: "
#define S_PIN               "  D"
#define S_PIN_ONES          ": "
#define S_PIN_PCT           "% ones"
#define S_PIN_STUCK         "  <-- LINE STUCK"
#define S_PIN_FLAKY         "  <-- UNSTABLE, mismatches: "
#define S_PINS_OK           "  all lines stable and toggling\n"
#define S_AUDIO_ONLINE      "Audio online: replaying acquired results on speaker...\n"
#define S_SUMMARY           "\n==== SUMMARY ====\n"
#define S_MAINRAM_OK        "Main RAM usable.\n"
#define S_MAINRAM_KO        "Main RAM NOT usable -> staying in OC-RAM only mode.\n"
#define S_ARAM_OK_MSG       "Sound RAM usable, audio reports active.\n"
#define S_VRAM_OK_MSG       "VRAM usable, on-screen report active.\n"
#define S_COMPLETE          "\n*** DIAG COMPLETE ***\n"

#endif

#endif /* STRINGS_H */
